module.exports = {
    adminButtonName: 'Admin',
    manageEventsLinkName: 'Manage Events',
    eventTitleInputTestId: 'event-title-input',
    eventDescriptionRoleName: 'Describe the event…',
    categoryLabel: 'Category*',
    cityRoleName: 'City*',
    venueRoleName: 'Venue*',
    priceRoleName: 'Price ($)*',
    dateTimeRoleName: 'Event Date & Time*',
    seatsRoleName: 'Total Seats*',
    addEventBtnTestId: 'add-event-btn',
    msgEventCreated: '✓Event created!×',
    confirmDialogYesTestId: 'confirm-dialog-yes',
    msgEventDeleted: 'Event deleted',
    editEventBtnTestId: 'edit-event-btn',
    msgEventUpdated: 'Event updated!',
    newEventContainerText: '+ New EventYou can add up to',
    totalEventsText: /\d+ total/,
    limitText: /You can add up to \d+ events/,
    limitErrorText: 'Maximum event limit reached'
};